"""add is_admin field to User model

Revision ID: 538cf8b94834
Revises: 
Create Date: 2025-06-17 09:10:30.738953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '538cf8b94834'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.alter_column('users', 'doctor_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_users_doctor_id', table_name='users')
    op.create_index(op.f('ix_users_doctor_id'), 'users', ['doctor_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_doctor_id'), table_name='users')
    op.create_index('ix_users_doctor_id', 'users', ['doctor_id'], unique=False)
    op.alter_column('users', 'doctor_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
